name: the_inventory
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: LibreFranklin
  #     fonts:
  #       - asset: assets/fonts/LibreFranklin-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets/fonts/LibreFranklin-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/LibreFranklin-Medium.ttf
  #         weight: 600
  #       - asset: assets/fonts/LibreFranklin-Regular.ttf
  #         weight: 500
  #       - asset: assets/fonts/LibreFranklin-Light.ttf
  #         weight: 400
  #       - asset: assets/fonts/LibreFranklin-Light.ttf
